#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Rvi.OrderAPI.Model/ && \
    dotnet build src/Rvi.OrderAPI.Model/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Rvi.OrderAPI.Model/Rvi.OrderAPI.Model.csproj --launch-profile web"
